# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'releaseCourseDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_release_course_Dialog(object):
    def setupUi(self, release_course_Dialog):
        release_course_Dialog.setObjectName("release_course_Dialog")
        release_course_Dialog.resize(558, 295)
        self.layoutWidget = QtWidgets.QWidget(release_course_Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 535, 114))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_9 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_9.setEnabled(True)
        self.comboBox_9.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.gridLayout.addWidget(self.comboBox_9, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 7, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_8.setEnabled(True)
        self.comboBox_8.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.gridLayout.addWidget(self.comboBox_8, 0, 1, 1, 2)
        self.course_id_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.course_id_lineEdit.setPlaceholderText("")
        self.course_id_lineEdit.setObjectName("course_id_lineEdit")
        self.gridLayout.addWidget(self.course_id_lineEdit, 1, 2, 1, 4)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 3, 2, 1, 2)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 3, 4, 1, 2)
        self.course_name_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.course_name_lineEdit.setPlaceholderText("")
        self.course_name_lineEdit.setObjectName("course_name_lineEdit")
        self.gridLayout.addWidget(self.course_name_lineEdit, 1, 8, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 2)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 8, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 2)
        self.course_id_label = QtWidgets.QLabel(self.layoutWidget)
        self.course_id_label.setObjectName("course_id_label")
        self.gridLayout.addWidget(self.course_id_label, 1, 0, 1, 2)
        self.course_name_label = QtWidgets.QLabel(self.layoutWidget)
        self.course_name_label.setObjectName("course_name_label")
        self.gridLayout.addWidget(self.course_name_label, 1, 7, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 8, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 2, 1, 4)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 0, 3, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        self.pushButton = QtWidgets.QPushButton(release_course_Dialog)
        self.pushButton.setGeometry(QtCore.QRect(190, 220, 171, 41))
        self.pushButton.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(release_course_Dialog)
        QtCore.QMetaObject.connectSlotsByName(release_course_Dialog)

    def retranslateUi(self, release_course_Dialog):
        _translate = QtCore.QCoreApplication.translate
        release_course_Dialog.setWindowTitle(_translate("release_course_Dialog", "Release New Course"))
        self.comboBox_9.setItemText(0, _translate("release_course_Dialog", "1"))
        self.comboBox_9.setItemText(1, _translate("release_course_Dialog", "2"))
        self.label_2.setText(_translate("release_course_Dialog", "开课学院"))
        self.comboBox_8.setItemText(0, _translate("release_course_Dialog", "2015-2016"))
        self.comboBox_8.setItemText(1, _translate("release_course_Dialog", "2016-2017"))
        self.comboBox_2.setItemText(0, _translate("release_course_Dialog", "4th Building"))
        self.comboBox_3.setItemText(0, _translate("release_course_Dialog", "401"))
        self.comboBox_3.setItemText(1, _translate("release_course_Dialog", "402"))
        self.label_4.setText(_translate("release_course_Dialog", "Teacher Name:"))
        self.label_5.setText(_translate("release_course_Dialog", "Class Time:"))
        self.comboBox.setItemText(0, _translate("release_course_Dialog", "Information"))
        self.comboBox.setItemText(1, _translate("release_course_Dialog", "机械工程学院"))
        self.label_3.setText(_translate("release_course_Dialog", "Location:"))
        self.course_id_label.setText(_translate("release_course_Dialog", "Course ID:"))
        self.course_name_label.setText(_translate("release_course_Dialog", "Course Name:"))
        self.label_22.setText(_translate("release_course_Dialog", "Semester:"))
        self.label_21.setText(_translate("release_course_Dialog", "Year:"))
        self.pushButton.setText(_translate("release_course_Dialog", "Release New Course"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    release_course_Dialog = QtWidgets.QDialog()
    ui = Ui_release_course_Dialog()
    ui.setupUi(release_course_Dialog)
    release_course_Dialog.show()
    sys.exit(app.exec_())

